#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_auth_login:
    path: /api/auth/login
    methods:  [POST]

gesdinet_jwt_refresh_token:
    path:       /api/auth/refresh
    controller: gesdinet.jwtrefreshtoken::refresh